version: "3.7"
services:
  frontend:
    image: methowsnow_godev
    command: go run ./cmd/frontend
    user: ${CURRENT_UID}
    volumes:
    - .:/code
    - ~/.config/gcloud:/.config/gcloud
    - ./js/dist:/app/static
    environment:
    - GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT}    
    ports:
    - "8080:8080"
  
  webpack:
    image: methowsnow_jsdev
    user: ${CURRENT_UID}
    init: true
    volumes:
    - .:/code
    command: webpack --mode development --watch
