application: methowsnow-dev
module: default
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: "/static"
  static_dir: static
- url: "/sensor/.*"
  script: main.app
- url: "/"
  script: main.app

libraries:
- name: django
  version: "1.4"

env_variables:
  DJANGO_SETTINGS_MODULE: 'settings'
